version: '3.8'

services:
  artwall-app:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: artwall-app
    environment:
      - NODE_ENV=production
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 可选：添加反向代理（如果需要 HTTPS）
  # nginx-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - artwall-app 